In [23]:
import pandas as pd

station_df = pd.read_csv('Taiwan_river_data.csv')
species_df = pd.read_csv('Taiwan_species.csv')
station_df.head()
station_df.drop(['Unnamed: 18'], axis=1, inplace=True)
station_df.head()

,station,latitude,longitude,river,RPI,DO(Electrode),BOD5,SS,NH3-N,pH,...,RPI_unit,DO(Electrode)_unit,BOD5_unit,SS_unit,NH3-N_unit,pH_unit,temperature_unit,species1,species2,species3
0,Upper Huang River Bridge,25.179209,121.582273,Huang River,1.00,7.8,1.0,8.4,0.11,2.37,...,NaN,mg/L,mg/L,mg/L,mg/L,NaN,℃,Cyprinus carpio,Pelophylax fukienensis,Zhangixalus taipeianus
1,Huang River Bridge,25.226953,121.630624,Huang River,3.50,7.3,10.8,97.1,0.19,4.00,...,NaN,mg/L,mg/L,mg/L,mg/L,NaN,℃,Zhangixalus taipeianus,Pelophylax fukienensis,Zhangixalus prasinatus
2,No. 40 Bridge,25.227357,121.630912,Huang River,4.50,6.6,12.7,131,0.17,4.62,...,NaN,mg/L,mg/L,mg/L,mg/L,NaN,℃,Pelophylax fukienensis,Zhangixalus prasinatus,Zhangixalus taipeianus
3,Jhongshou Bridge.,25.051144,121.500209,Danshuei River,6.25,4.6,5.0,167,1.41,7.42,...,NaN,mg/L,mg/L,mg/L,mg/L,NaN,℃,Pelophylax fukienensis,Zhangixalus prasinatus,Zhangixalus taipeianus
4,Chongyang Bridge,25.084174,121.502797,Danshuei River,4.00,3.3,2.7,35.6,1.47,7.22,...,NaN,mg/L,mg/L,mg/L,mg/L,NaN,℃,Rana longicrus,Cyprinus carpio,Zhangixalus taipeianus

In [24]:
def dist(a,b):
    return ((a[0]-b[0])**2 + (a[1]-b[1])**2)**0.5
import random
import tqdm
r = 1
sp1 = []
sp2 = []
sp3 = []
total = 0
for i in tqdm.tqdm(range(len(station_df))):
    lat = station_df['latitude'][i]
    lon = station_df['longitude'][i]
    species = []
    l = list(range(len(species_df)))
    random.shuffle(l)
    count = 0
    for j in l:
        lat2 = species_df['latitude'][j]
        lon2 = species_df['longitude'][j]
        count += 1
        if not species_df['scientific_name'][j] in species and dist((lat,lon),(lat2,lon2)) < r:
            species.append(species_df['scientific_name'][j])
        if len(species) == 3:
            break
    try:
        sp1.append(species[0])
    except:
        sp1.append(None)
    try:
        sp2.append(species[1])
    except:
        sp2.append(None)
    try:
        sp3.append(species[2])
    except:
        sp3.append(None)

station_df['species1'] = sp1
station_df['species2'] = sp2
station_df['species3'] = sp3
station_df.to_csv('Taiwan_river_data_s.csv')
print(total/len(station_df))

100%|██████████| 303/303 [00:00<00:00, 3518.27it/s]

0.0